#!/bin/bash
fruits=("apple" "banana" "grapes" "pineapple")
echo "first fruit is ${fruits[0]}"
echo "second fruit is ${fruits[1]}"
echo "third fruit is ${fruits[2]}"
echo "fourth fruit is ${fruits[3]}"